[GLOBAL]
pants_version = "2.22.0"
backend_packages.add = [
  "pants.backend.build_files.fmt.yapf",  
  "pants.backend.python",
  "pants.backend.python.lint.autoflake",
  "pants.backend.python.lint.bandit",
  "pants.backend.python.lint.docformatter",
  "pants.backend.python.lint.black",
  "pants.backend.python.lint.flake8",
  "pants.backend.python.lint.isort",
  "pants.backend.python.lint.pylint",
  "pants.backend.python.lint.pyupgrade",
  "pants.backend.python.lint.yapf",
  "pants.backend.python.typecheck.mypy",
]
pants_ignore = [
    '.devcontainer/**',
    '.vscode/**',
    '*venv/*'
]

[source]
root_patterns = ["/"]

[python]
interpreter_constraints = ["==3.11.*"]
enable_resolves = true
resolves = { python-default = "python-default.lock"}

[python-bootstrap]
#  https://www.pantsbuild.org/docs/python-interpreter-compatibility#changing-the-interpreter-search-path.
search_path = ["<PATH>", "<PYENV>"]

[python-infer]
use_rust_parser = true

[update-build-files]
formatter="yapf"

[bandit]
args = ["--quiet"]
